"""empty message

Revision ID: 1f1718fe764c
Revises: 66bc47fb4346
Create Date: 2022-04-11 10:52:55.601997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1718fe764c'
down_revision = '66bc47fb4346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('ocr_results', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'ocr_results')
    # ### end Alembic commands ###
