"""remove auth_code from user

Revision ID: 51ab32acffee
Revises: 44a1c6584342
Create Date: 2022-04-22 13:43:47.406045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ab32acffee'
down_revision = '44a1c6584342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users') as batch_op:
        batch_op.drop_column('auth_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('auth_code', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
