"""empty message

Revision ID: 6033e27b39f6
Revises: df860231c5b1
Create Date: 2022-05-06 10:49:38.006318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6033e27b39f6'
down_revision = 'df860231c5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Infopage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Users', sa.Column('num_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'num_attempts')
    op.drop_table('Infopage')
    # ### end Alembic commands ###
