"""empty message

Revision ID: 6e827a66391b
Revises: 51ab32acffee
Create Date: 2022-04-22 13:58:16.206364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e827a66391b'
down_revision = '51ab32acffee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users') as batch_op:
        batch_op.drop_column('password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
